export const lectureData = {
  count: 150,
  next: 'http://example.com/api/v1/lectures/?page=3',
  previous: 'http://example.com/api/v1/lectures/?page=1',

  results: [
    {
      uuid: '550e8400-e29b-41d4-a716-446655440000',
      title: 'Django 완벽 가이드',
      instructor: '홍길동',
      thumbnail_img_url: '',
      categories: [
        { id: 1, name: '백엔드' },
        { id: 5, name: 'Django' },
      ],
      difficulty: 'NORMAL',
      original_price: 100000,
      discount_price: 50000,
      platform: 'inflearn',
      average_rating: 4.75,
      url_link: 'https://inflearn.com/course/django-guide',
      is_bookmarked: false,
      duration: 600,
    },
    {
      uuid: '9b73c9a8-3bde-4b8f-a6b1-0d4376c7d101',
      title: 'React 완벽 마스터 강의 - 기초부터 고급까지',
      instructor: '김개발',
      thumbnail_img_url: '',
      categories: [
        { id: 10, name: '프론트엔드' },
        { id: 11, name: 'React' },
      ],
      difficulty: 'NORMAL',
      original_price: 89000,
      discount_price: 89000,
      platform: 'inflearn',
      average_rating: 4.8,
      url_link: 'https://example.com/react-master',
      is_bookmarked: false,
      duration: 800,
    },
    {
      uuid: 'c10e2b6b-8261-4f55-a1d7-fb8b44f2c203',
      title: 'Node.js 백엔드 개발 완주 - 실무 프로젝트까지',
      instructor: '박서버',
      thumbnail_img_url: '',
      categories: [
        { id: 1, name: '백엔드' },
        { id: 12, name: 'Node.js' },
      ],
      difficulty: 'NORMAL',
      original_price: 120000,
      discount_price: 120000,
      platform: 'inflearn',
      average_rating: 4.6,
      url_link: 'https://example.com/nodejs-backend',
      is_bookmarked: false,
      duration: 580,
    },
    {
      uuid: 'd2a4f5ef-19e3-43c5-b928-c65a74522a04',
      title: 'Python 데이터 사이언스 마스터클레스',
      instructor: '이데이터',
      thumbnail_img_url: '',
      categories: [
        { id: 2, name: 'Python' },
        { id: 20, name: '데이터 사이언스' },
      ],
      difficulty: 'HARD',
      original_price: 150000,
      discount_price: 150000,
      platform: 'inflearn',
      average_rating: 4.9,
      url_link: 'https://example.com/python-ds',
      is_bookmarked: true,
      duration: 920,
    },
    {
      uuid: 'e7b4d232-b80c-4a0f-9cd9-f5f51f21a605',
      title: 'JavaScript ES6+ 완벽 가이드 - 모던 자바스크립트',
      instructor: '최자바',
      thumbnail_img_url: '',
      categories: [
        { id: 3, name: 'JavaScript' },
        { id: 21, name: '기초' },
      ],
      difficulty: 'EASY',
      original_price: 75000,
      discount_price: 75000,
      platform: 'inflearn',
      average_rating: 4.7,
      url_link: 'https://example.com/js-es6',
      is_bookmarked: false,
      duration: 490,
    },
    {
      uuid: 'f9d1a7b1-3b1f-47f1-8ed9-d32b117874c3',
      title: 'Vue.js 실전 프로젝트 - SPA 개발 완성',
      instructor: '정뷰',
      thumbnail_img_url: '',
      categories: [
        { id: 10, name: '프론트엔드' },
        { id: 30, name: 'Vue.js' },
      ],
      difficulty: 'NORMAL',
      original_price: 95000,
      discount_price: 95000,
      platform: 'inflearn',
      average_rating: 4.5,
      url_link: 'https://example.com/vue-spa',
      is_bookmarked: false,
      duration: 680,
    },
  ],

  user_nickname: '이영수',

  recommended_lectures: [
    {
      uuid: '660e8400-e29b-41d4-a716-446655440001',
      title: 'Python 기초부터 실전까지',
      instructor: '김철수',
      thumbnail_img_url: 'https://example.com/image2.jpg',
      categories: [{ id: 2, name: 'Python' }],
      difficulty: 'EASY',
      original_price: 80000,
      discount_price: 40000,
      platform: 'udemy',
      average_rating: 4.9,
      url_link: 'https://udemy.com/course/python-basics',
      is_bookmarked: true,
      duration: 500,
    },
    {
      uuid: 'b92e7a7c-f11e-4f83-a833-f4128c98e21b',
      title: 'Django REST API 마스터',
      instructor: '홍길동',
      thumbnail_img_url: 'https://example.com/image3.jpg',
      categories: [
        { id: 5, name: 'Django' },
        { id: 1, name: '백엔드' },
      ],
      difficulty: 'NORMAL',
      original_price: 110000,
      discount_price: 70000,
      platform: 'inflearn',
      average_rating: 4.8,
      url_link: 'https://inflearn.com/course/django-rest-api',
      is_bookmarked: false,
      duration: 750,
    },
  ],
}
