export const lectureList = [
  {
    id: 1,
    title: 'React 완벽 마스터 강의 - 기초부터 고급까지',
    thumbnail_img_url: '',
    instructor: '김개발',
    duration: '12:30',
    price: 89000,
    platform: 'inflearn',
  },
  {
    id: 2,
    title: 'Node.js 백엔드 개발 완주 - 실무 프로젝트까지',
    thumbnail_img_url: '',
    instructor: '박서버',
    duration: '18:45',
    price: 120000,
    platform: 'inflearn',
  },
  {
    id: 3,
    title: 'Python 데이터 사이언스 마스터클레스',
    thumbnail_img_url: '',
    instructor: '이데이터',
    duration: '25:15',
    price: 150000,
    platform: 'inflearn',
  },
  {
    id: 4,
    title: 'JavaScript ES6+ 완벽 가이드 - 모던 자바스크립트',
    thumbnail_img_url: '',
    instructor: '최자바',
    duration: '15:20',
    price: 75000,
    platform: 'inflearn',
  },
  {
    id: 5,
    title: 'Vue.js 실전 프로젝트 - SPA 개발 완성',
    thumbnail_img_url: '',
    instructor: '정뷰',
    duration: '20:10',
    price: 95000,
    platform: 'inflearn',
  },
  // {
  //   id: 6,
  //   title: 'Vue.js 실전 프로젝트 - SPA 개발 완성',
  //   thumbnail_img_url: '',
  //   instructor: '정뷰',
  //   duration: '20:10',
  //   price: 95000,
  //   platform: 'inflearn',
  // },
]
